home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about_us, name="about"),
    
    path('events/', views.events, name="events"),
    path('event/<str:pk>/', views.event, name="event"),
    path('add-event/', views.add_event, name="add-event"),
    path('edit-event/<str:pk>/', views.edit_event, name="edit-event"),
    path('delete-event/<str:pk>/', views.delete_event, name="delete-event"),

    path('special-orders/', views.special_orders, name="special-orders"),
    path('add-order/', views.add_order, name="add-order"),
    path('edit-order/<str:pk>/', views.edit_order, name="edit-order"),
    path('delete-order/<str:pk>/', views.delete_order, name="delete-order"),

    path('add-event-agency/<str:pk>/', views.add_event_agency, name="add-event-agency"),
    path('edit-event-agency/<str:pk>/', views.edit_event_agency, name="edit-event-agency"),
    path('delete-event-agency/<str:pk>/', views.delete_event_agency, name="delete-event-agency"),

    path('memorandums/', views.memorandums, name="memorandums"),
    path('add-memo/', views.add_memo, name="add-memo"),
    path('edit-memo/<str:pk>/', views.edit_memo, name="edit-memo"),
    path('delete-memo/<str:pk>/', views.delete_memo, name="delete-memo"),

    path('comm-letters/', views.comm_letters, name="comm-letters"),
    path('add-letter/', views.add_letter, name="add-letter"),
    path('edit-letter/<str:pk>/', views.edit_letter, name="edit-letter"),
    path('delete-letter/<str:pk>/', views.delete_letter, name="delete-letter"),

    path('moas/', views.moas, name="moas"),
    path('moa/<str:pk>/', views.moa, name="moa"),
    path('add-moa/', views.add_moa, name="add-moa"),
    path('edit-moa/<str:pk>/', views.edit_moa, name="edit-moa"),
    path('delete-moa/<str:pk>/', views.delete_moa, name="delete-moa"),

    path('add-party/<str:pk>/', views.add_party, name="add-party"),
    path('edit-party/<str:pk>/', views.edit_party, name="edit-party"),
    path('delete-party/<str:pk>/', views.delete_party, name="delete-party"),

    path('add-signatory/<str:pk>/', views.add_signatory, name="add-signatory"),
    path('edit-signatory/<str:pk>/', views.edit_signatory, name="edit-signatory"),
    path('delete-signatory/<str:pk>/', views.delete_signatory, name="delete-signatory"),

    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

    path('profile/', views.profile, name="profile"),
    path('edit-profile/', views.edit_profile, name="edit-profile"),
    path('edit-info/', views.edit_info, name="edit-info"),
]

wesmaarrdec/urls.py
from django.contrib import admin
from django.urls import path, include

# handle files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]


# handle files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Import AbstractUser
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    GENDER_TYPE = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )

    name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    phone_num = models.CharField(max_length=11, null=True, blank=True)
    avatar = models.ImageField(default="avatar.svg", null=True, blank=True)
    employee_num = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=50, choices=GENDER_TYPE, null=True, blank=True)
    nationality = models.CharField(max_length=150, null=True, blank=True)
    occupation = models.CharField(max_length=150, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.email

class Attainment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    year_attended = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

class Memorandum(models.Model):
    memo_no = models.CharField(max_length=10, primary_key=True)
    memo_date = models.DateField(null=True, blank=True)
    memo_file = models.FileField(null=True, blank=True)
    memo_subject = models.CharField(max_length=255, null=True, blank=True)
    memo_content = models.TextField(null=True, blank=True)
    memo_to = models.CharField(max_length=100, null=True, blank=True)
    memo_to_pos = models.CharField(max_length=100, null=True, blank=True)
    memo_thru = models.CharField(max_length=100, null=True, blank=True)
    memo_thru_pos = models.CharField(max_length=100, null=True, blank=True)
    memo_from = models.CharField(max_length=100, null=True, blank=True)
    memo_from_pos = models.CharField(max_length=100, null=True, blank=True)
    memo_recomm_by = models.CharField(max_length=100, null=True, blank=True)
    memo_approved_by = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.memo_no

class SpecialOrder(models.Model):
    so_no = models.CharField(max_length=10, primary_key=True)
    so_date = models.DateField(null=True, blank=True)
    so_file = models.FileField(null=True, blank=True)
    so_subject =  models.CharField(max_length=255, null=True, blank=True)
    so_content = models.TextField(null=True, blank=True)
    so_for = models.CharField(max_length=100, null=True, blank=True)
    so_signedby = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.so_no

class CommLetter(models.Model):
    letter_no = models.CharField(max_length=10, primary_key=True)
    letter_file = models.FileField(null=True, blank=True)
    letter_subject = models.CharField(max_length=255, null=True, blank=True)
    letter_to = models.CharField(max_length=100, null=True, blank=True)
    letter_from = models.CharField(max_length=100, null=True, blank=True)
    letter_received_by = models.CharField(max_length=100, null=True, blank=True)
    letter_received_date = models.DateField(null=True, blank=True)
    letter_noted_by = models.CharField(max_length=100, null=True, blank=True)
    letter_recom_approval = models.CharField(max_length=100, null=True, blank=True)
    letter_approved_by = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.letter_no

class Moau(models.Model):
    TYPE = (
        ('MOA', 'MOA'),
        ('MOU', 'MOU')
    )

    moau_no = models.CharField(max_length=10, primary_key=True)
    moau_file = models.FileField(null=True, blank=True)
    moau_title = models.CharField(max_length=255, null=True, blank=True)
    moau_type = models.CharField(max_length=100, choices=TYPE, null=True, blank=True)
    moau_objective = models.TextField(null=True, blank=True)
    moau_approve_date = models.DateField(null=True, blank=True)
    moau_notarized_by = models.CharField(max_length=100, null=True, blank=True)
    moau_notarized_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return self.moau_no


class MoauParties(models.Model):
    moau = models.ForeignKey(Moau, on_delete=models.CASCADE)
    agency = models.CharField(max_length=100, null=True, blank=True)
    represented_by = models.CharField(max_length=100, null=True, blank=True)
    position = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    referred_to_as = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['created_at']
        
    def __str__(self):
        return self.moau

class MoauSignatories(models.Model):
    moau = models.ForeignKey(Moau, on_delete=models.CASCADE)
    signed_by = models.CharField(max_length=100, null=True, blank=True)
    position = models.CharField(max_length=100, null=True, blank=True)
    agency = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['created_at']
        
    def __str__(self):
        return self.moau


class Event(models.Model):
    event_id = models.CharField(max_length=10, primary_key=True)
    event_name = models.CharField(max_length=100, null=True, blank=True)
    event_agenda = models.CharField(max_length=100, null=True, blank=True)
    event_date = models.DateField(null=True, blank=True)
    event_venue = models.CharField(max_length=100, null=True, blank=True)
    no_participants = models.CharField(max_length=100, null=True, blank=True)
    impl_agency = models.CharField(max_length=100, null=True, blank=True)
    attendance_file = models.FileField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return self.event_name

class EventAgencies(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    agency_id = models.CharField(max_length=100, null=True, blank=True)
    agency_role = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return self.event

home/forms.py
from .models import User, Memorandum, SpecialOrder, CommLetter, Moau, Event

from django.forms import ModelForm, ImageField, FileInput, DateTimeField, DateInput, FileField, DateField

class UserPForm(ModelForm):
    avatar = ImageField(required=False, widget=FileInput)

    class Meta:
        model = User
        fields = ['avatar']

class UserIForm(ModelForm):
    birth_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())

    class Meta:
        model = User
        fields = ['gender', 'birth_date']

class MoauForm(ModelForm):
    moau_file = FileField(required=False, widget=FileInput)
    moau_approve_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())
    moau_notarized_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())

    class Meta:
        model = Moau
        fields = ['moau_file', 'moau_type', 'moau_approve_date', 'moau_notarized_date']


class EventForm(ModelForm):
    event_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())
    attendance_file = FileField(required=False, widget=FileInput)

    class Meta:
        model = Event
        fields = ['event_date', 'attendance_file']

class MemoForm(ModelForm):
    memo_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())
    memo_file = FileField(required=False, widget=FileInput)

    class Meta:
        model = Memorandum
        fields = ['memo_date', 'memo_file']

class LetterForm(ModelForm):
    letter_file = FileField(required=False, widget=FileInput)
    letter_received_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())

    class Meta:
        model = CommLetter
        fields = ['letter_file', 'letter_received_date']

class OrderForm(ModelForm):
    so_date = DateField(required=False, input_formats=['%Y-%m-%d'], widget=DateInput())
    so_file = FileField(required=False, widget=FileInput)

    class Meta:
        model = SpecialOrder
        fields = ['so_date', 'so_for', 'so_file']

templates/home/add_event.html
<!-- Extends to Main.html -->
{% extends 'index.html' %}

<!-- Load static -->
{% load static %}

<!-- Load Datepicker CSS -->
{% block css %}
<link
	rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
	integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE="
	crossorigin="anonymous"
/>
{% endblock css %}

<!-- Main Content -->
{% block content %}
<main>
	<div class="formwrapper event_formwrapper">
		<div class="create-room layout">
			<div class="formcontainer">
				<div class="form__box event_form_box">
					<div class="form__top">
						<div class="room__topleft">
							<a href="{% url 'events' %}">
								<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
									<title>arrow-left</title>
									<path
										d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
									></path>
								</svg>
							</a>
						</div>
						<h3>Upload Event</h3>
					</div>
					<div class="layout__body">
						{% if messages %} {% for message in messages %} {% if message.tags == 'success' %}
						<p style="text-align: center; justify-content: center; color: green">{{ message }}</p>
						{% else %}
						<p style="text-align: center; justify-content: center; color: red">{{ message }}</p>
						{% endif %} {% endfor %} {% endif %}

						<form action="" class="modalform" method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="modalform__group">
								<label for="event_id">Event ID:</label>
								<input type="text" id="event_id" name="event_id" value="{{data.event_id}}" />
							</div>
							<div class="modalform__group">
								<label for="event_name">Event Name:</label>
								<input type="text" id="event_name" name="event_name" value="{{data.event_name}}" />
							</div>
							<div class="modalform__group">
								<label for="event_agenda">Agenda:</label>
								<input type="text" id="event_agenda" name="event_agenda" value="{{data.event_agenda}}" />
							</div>
							<div class="modalform__group">
								<label for="event_date">Event Date:</label>
								{{form.event_date}}
							</div>
							<div class="modalform__group">
								<label for="event_venue">Venue:</label>
								<input type="text" id="event_venue" name="event_venue" value="{{data.event_venue}}" />
							</div>
							<div class="modalform__group">
								<label for="no_participants">No Participants:</label>
								<input type="text" id="no_participants" name="no_participants" value="{{data.no_participants}}" />
							</div>
							<div class="modalform__group">
								<label for="impl_agency">Agency:</label>
								<input type="text" id="impl_agency" name="impl_agency" value="{{data.impl_agency}}" />
							</div>
							<div class="modalform__group">
								<label for="attendance_file">Attendance File:</label>
								{{form.attendance_file}}
							</div>
							<div class="modalform__action">
								<a class="modalbtn modalbtn--dark" href="{% url 'events' %}">Cancel</a>
								<button class="modalbtn modalbtn--main" type="submit">Upload Event</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

<!-- Load Datepicker JS -->
{% block js %}
<script
	src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	crossorigin="anonymous"
></script>

<script
	src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
	integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k="
	crossorigin="anonymous"
></script>

<script>
	$(function () {
		$("#id_event_date").datepicker({
			format: "yyyy-mm-dd",
		});
	});
</script>
{% endblock js %} {% endblock content %}

templates/home/add_letter.html
<!-- Extends to Main.html -->
{% extends 'index.html' %}

<!-- Load static -->
{% load static %}

<!-- Load Datepicker CSS -->
{% block css %}
<link
	rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
	integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE="
	crossorigin="anonymous"
/>
{% endblock css %}

<!-- Main Content -->
{% block content %}
<main>
	<div class="formwrapper letter_formwrapper">
		<div class="create-room layout">
			<div class="formcontainer">
				<div class="form__box letter_form_box">
					<div class="form__top">
						<div class="room__topleft">
							<a href="{% url 'comm-letters' %}">
								<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
									<title>arrow-left</title>
									<path
										d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
									></path>
								</svg>
							</a>
						</div>
						<h3>Upload Letter</h3>
					</div>
					<div class="layout__body">
						{% if messages %} {% for message in messages %} {% if message.tags == 'success' %}
						<p style="text-align: center; justify-content: center; color: green">{{ message }}</p>
						{% else %}
						<p style="text-align: center; justify-content: center; color: red">{{ message }}</p>
						{% endif %} {% endfor %} {% endif %}

						<form action="" class="modalform" method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="modalform__group">
								<label for="letter_no">Letter No:</label>
								<input type="text" id="letter_no" name="letter_no" value="{{data.letter_no}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_file">Letter File:</label>
								{{form.letter_file}}
							</div>
							<div class="modalform__group">
								<label for="letter_subject">Subject:</label>
								<input type="text" id="letter_subject" name="letter_subject" value="{{data.letter_subject}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_to">Letter To:</label>
								<input type="text" id="letter_to" name="letter_to" value="{{data.letter_to}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_from">Letter From:</label>
								<input type="text" id="letter_from" name="letter_from" value="{{data.letter_from}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_received_by">Received By:</label>
								<input type="text" id="letter_received_by" name="letter_received_by" value="{{data.letter_received_by}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_received_date">Received Date:</label>
								{{form.letter_received_date}}
							</div>
							<div class="modalform__group">
								<label for="letter_noted_by">Noted By:</label>
								<input type="text" id="letter_noted_by" name="letter_noted_by" value="{{data.letter_noted_by}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_recom_approval">Recommend Approval:</label>
								<input type="text" id="letter_recom_approval" name="letter_recom_approval" value="{{data.letter_recom_approval}}" />
							</div>
							<div class="modalform__group">
								<label for="letter_approved_by">Approved By:</label>
								<input type="text" id="letter_approved_by" name="letter_approved_by" value="{{data.letter_approved_by}}" />
							</div>

							<div class="modalform__action">
								<a class="modalbtn modalbtn--dark" href="{% url 'comm-letters' %}">Cancel</a>
								<button class="modalbtn modalbtn--main" type="submit">Upload Letter</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

<!-- Load Datepicker JS -->
{% block js %}
<script
	src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	crossorigin="anonymous"
></script>

<script
	src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
	integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k="
	crossorigin="anonymous"
></script>

<script>
	$(function () {
		$("#id_letter_received_date").datepicker({
			format: "yyyy-mm-dd",
		});
	});
</script>
{% endblock js %} {% endblock content %}

templates/home/add_memo.html
<!-- Extends to Main.html -->
{% extends 'index.html' %}

<!-- Load static -->
{% load static %}

<!-- Load Datepicker CSS -->
{% block css %}
<link
	rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
	integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE="
	crossorigin="anonymous"
/>
{% endblock css %}

<!-- Main Content -->
{% block content %}
<main>
	<div class="formwrapper memo_formwrapper">
		<div class="create-room layout">
			<div class="formcontainer">
				<div class="form__box memo_form_box">
					<div class="form__top">
						<div class="room__topleft">
							<a href="{% url 'memorandums' %}">
								<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
									<title>arrow-left</title>
									<path
										d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
									></path>
								</svg>
							</a>
						</div>
						<h3>Upload Memo</h3>
					</div>
					<div class="layout__body">
						{% if messages %} {% for message in messages %} {% if message.tags == 'success' %}
						<p style="text-align: center; justify-content: center; color: green">{{ message }}</p>
						{% else %}
						<p style="text-align: center; justify-content: center; color: red">{{ message }}</p>
						{% endif %} {% endfor %} {% endif %}

						<form action="" class="modalform" method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="modalform__group">
								<label for="memo_no">Memo No:</label>
								<input type="text" id="memo_no" name="memo_no" value="{{data.memo_no}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_date">Memo Date:</label>
								{{form.memo_date}}
							</div>
							<div class="modalform__group">
								<label for="memo_file">Memo File:</label>
								{{form.memo_file}}
							</div>
							<div class="modalform__group">
								<label for="memo_subject">Subject:</label>
								<input type="text" id="memo_subject" name="memo_subject" value="{{data.memo_subject}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_content">Content:</label>
								<textarea name="memo_content" cols="40" rows="10" id="memo_content">{{data.memo_content}}</textarea>
							</div>
							<div class="modalform__group">
								<label for="memo_to">Memo To:</label>
								<input type="text" id="memo_to" name="memo_to" value="{{data.memo_to}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_to_pos">Memo To Pos:</label>
								<input type="text" id="memo_to_pos" name="memo_to_pos" value="{{data.memo_to_pos}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_thru">Memo Thru:</label>
								<input type="text" id="memo_thru" name="memo_thru" value="{{data.memo_thru}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_thru_pos">Memo Thru Pos:</label>
								<input type="text" id="memo_thru_pos" name="memo_thru_pos" value="{{data.memo_thru_pos}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_from">Memo From:</label>
								<input type="text" id="memo_from" name="memo_from" value="{{data.memo_from}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_from_pos">Memo From Pos:</label>
								<input type="text" id="memo_from_pos" name="memo_from_pos" value="{{data.memo_from_pos}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_recomm_by">Recommended By:</label>
								<input type="text" id="memo_recomm_by" name="memo_recomm_by" value="{{data.memo_recomm_by}}" />
							</div>
							<div class="modalform__group">
								<label for="memo_approved_by">Approved By:</label>
								<input type="text" id="memo_approved_by" name="memo_approved_by" value="{{data.memo_approved_by}}" />
							</div>

							<div class="modalform__action">
								<a class="modalbtn modalbtn--dark" href="{% url 'memorandums' %}">Cancel</a>
								<button class="modalbtn modalbtn--main" type="submit">Upload Memo</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

<!-- Load Datepicker JS -->
{% block js %}
<script
	src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	crossorigin="anonymous"
></script>

<script
	src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
	integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k="
	crossorigin="anonymous"
></script>

<script>
	$(function () {
		$("#id_memo_date").datepicker({
			format: "yyyy-mm-dd",
		});
	});
</script>
{% endblock js %} {% endblock content %}